apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: skywalking  #你自己项目的名称空间
  labels:
    service: ui
spec:
  ports:
  - port: 8080
    name: page
    nodePort: 30800   #外面访问页面的端口
  type: NodePort
  selector:
    app: ui
