apiVersion: v1
kind: Service
metadata:
  name: traefik
spec:
  ports:
  - port: 8080
    name: admin
    nodePort: 30081
  - port: 80
    name: web
    nodePort: 30080
  selector:
    app: traefik
  type: NodePort
