kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sk-data
  annotations: 
    volume.beta.kubernetes.io/storage-class: sk-data
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 2Gi
