apiVersion: v1
kind: Service
metadata:
  name: loki-stack-ui
spec:
  ports:
  - port: 3100
    name: http-metrics
    targetPort: http-metrics
    nodePort: 32000
  selector:
    release: loki-stack
  type: NodePort

