apiVersion: v1
kind: Service
metadata:
  name: loki-ui
spec:
  ports:
  - port: 3100
    name: http-metrics
    targetPort: http-metrics
    nodePort: 31000
  selector:
    app: loki
  type: NodePort
