---
apiVersion: v1
kind: Service
metadata:
  name: mysql-test
  namespace: skywalking
spec:
  type: NodePort
  selector:
    app: mysql-test
  ports:
  - name: mysql-test
    nodePort: 33066
    port: 3306
    targetPort: 3306
