apiVersion: v1
kind: Service
metadata:
  name: oap-port
  namespace: skywalking
spec:
  ports:
  - port: 11800
    name: grpc
    targetPort: grpc
    nodePort: 21800
  - port: 12800
    name: rest
    targetPort: rest
    nodePort: 22800
  selector:
    app: oap
  type: NodePort
