apiVersion: v1
kind: Service
metadata:
  name: mysql-ui
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
    name: mysql
    targetPort: mysql
    nodePort: 30306
  selector:
    app: mysql
  type: NodePort