apiVersion: v1
kind: Service
metadata:
  name: yapi-mongo-ui
  labels:
    app: yapi-mongo
spec:
  ports:
  - port: 27017
    name: yapi-mongo
    targetPort: yapi-mongo
    nodePort: 30511
  selector:
    app: yapi-mongo
  type: NodePort