apiVersion: v1
kind: Service
metadata:
  name: openpitrix-rp-manager
  labels:
    app: openpitrix
    component: openpitrix-rp-manager
    version: {{ .Values.version }}
spec:
  selector:
    app: openpitrix
    component: openpitrix-rp-manager
  ports:
  - name: openpitrix-rp-manager
    protocol: TCP
    port: 9121
    targetPort: 9121
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: openpitrix-rp-manager-deployment
  labels:
    app: openpitrix
    component: openpitrix-rp-manager
    version: {{ .Values.version }}
spec:
  selector:
    matchLabels:
      app: openpitrix
      component: openpitrix-rp-manager
  replicas: 1
  template:
    metadata:
      labels:
        app: openpitrix
        component: openpitrix-rp-manager
        version: {{ .Values.version }}
    spec:
      initContainers:
      - name: wait-etcd
        image: busybox:1.28.4
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nc -z {{ .Values.etcd.host }}.{{ .Release.Namespace }}.svc {{ .Values.etcd.service_port }}; do echo "waiting for etcd"; sleep 2; done;']
      containers:
      - name: openpitrix-rp-manager
        image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.image_pull_policy }}
        command:
        - runtime-provider-manager
        ports:
        - containerPort: 9121
          name: rp-manager
        env:
        - name: OPENPITRIX_GRPC_SHOW_ERROR_CAUSE
          value: {{ .Values.grpc_show_error_cause | quote }}
        - name: OPENPITRIX_LOG_LEVEL
          value: {{ .Values.openpitrix_log_level }}
        resources:
          limits:
            cpu: {{ .Values.cpu_limits }}m
            memory: {{ .Values.memory_limits }}Mi
          requests:
            cpu: {{ .Values.cpu_requests }}m
            memory: {{ .Values.memory_requests }}Mi
