apiVersion: v1
kind: Service
metadata:
  name: openpitrix-notification
  labels:
    app: openpitrix
    component: openpitrix-notification
    version: {{ .Values.notification.version }}
spec:
  selector:
    app: openpitrix
    component: openpitrix-notification
  ports:
  - name: openpitrix-notification
    protocol: TCP
    port: 9201
    targetPort: 9201
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: openpitrix-notification-deployment
  labels:
    app: openpitrix
    component: openpitrix-notification
    version: {{ .Values.notification.version }}
spec:
  selector:
    matchLabels:
      app: openpitrix
      component: openpitrix-notification
  replicas: 1
  template:
    metadata:
      labels:
        app: openpitrix
        component: openpitrix-notification
        version: {{ .Values.notification.version }}
    spec:
      initContainers:
      - name: wait-mysql
        image: busybox:1.28.4
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nc -z {{ .Values.mysql.host }}.{{ .Release.Namespace }}.svc {{ .Values.mysql.service_port }}; do echo "waiting for mysql"; sleep 2; done;']
      - name: wait-etcd
        image: busybox:1.28.4
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nc -z {{ .Values.etcd.host }}.{{ .Release.Namespace }}.svc {{ .Values.etcd.service_port }}; do echo "waiting for etcd"; sleep 2; done;']
      containers:
      - name: openpitrix-notification
        image: {{ .Values.notification.image }}
        imagePullPolicy: {{ .Values.image_pull_policy }}
        command:
          - notification
        ports:
        - containerPort: 9201
          name: notification
        env:
        - name: NOTIFICATION_GRPC_SHOW_ERROR_CAUSE
          value: {{ .Values.grpc_show_error_cause | quote }}
        - name: NOTIFICATION_LOG_LEVEL
          value: {{ .Values.openpitrix_log_level }}
        - name: NOTIFICATION_ETCD_ENDPOINTS
          value: "{{ .Values.etcd.host }}:{{ .Values.etcd.service_port }}"
        - name: NOTIFICATION_MYSQL_HOST
          value: {{ .Values.mysql.host | quote }}
        - name: NOTIFICATION_MYSQL_PORT
          value: {{ .Values.mysql.service_port | quote }}
        - name: NOTIFICATION_MYSQL_DATABASE
          value: "notification"
        - name: NOTIFICATION_MYSQ_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password.txt
              name: mysql-pass
        resources:
          limits:
            cpu: {{ .Values.cpu_limits }}m
            memory: {{ .Values.memory_limits }}Mi
          requests:
            cpu: {{ .Values.cpu_requests }}m
            memory: {{ .Values.memory_requests }}Mi
