apiVersion: v1
kind: Service
metadata:
  name: openpitrix-isv-manager
  labels:
    app: openpitrix
    component: openpitrix-isv-manager
    version: {{ .Values.version }}
spec:
  selector:
    app: openpitrix
    component: openpitrix-isv-manager
  ports:
  - name: openpitrix-isv-manager
    protocol: TCP
    port: 9118
    targetPort: 9118
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: openpitrix-isv-manager-deployment
  labels:
    app: openpitrix
    component: openpitrix-isv-manager
    version: {{ .Values.version }}
spec:
  selector:
    matchLabels:
      app: openpitrix
      component: openpitrix-isv-manager
  replicas: 1
  template:
    metadata:
      labels:
        app: openpitrix
        component: openpitrix-isv-manager
        version: {{ .Values.version }}
    spec:
      initContainers:
      - name: wait-mysql
        image: busybox:1.28.4
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nc -z {{ .Values.mysql.host }}.{{ .Release.Namespace }}.svc {{ .Values.mysql.service_port }}; do echo "waiting for mysql"; sleep 2; done;']
      - name: wait-etcd
        image: busybox:1.28.4
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nc -z {{ .Values.etcd.host }}.{{ .Release.Namespace }}.svc {{ .Values.etcd.service_port }}; do echo "waiting for etcd"; sleep 2; done;']
      containers:
      - name: openpitrix-isv-manager
        image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.image_pull_policy }}
        command:
        - isv-manager
        ports:
        - containerPort: 9118
          name: isv-manager
        env:
        - name: OPENPITRIX_GRPC_SHOW_ERROR_CAUSE
          value: {{ .Values.grpc_show_error_cause | quote }}
        - name: OPENPITRIX_LOG_LEVEL
          value: {{ .Values.openpitrix_log_level }}
        - name: OPENPITRIX_MYSQL_DATABASE
          value: "isv"
        - name: OPENPITRIX_MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password.txt
              name: mysql-pass
        resources:
          limits:
            cpu: {{ .Values.cpu_limits }}m
            memory: {{ .Values.memory_limits }}Mi
          requests:
            cpu: {{ .Values.cpu_requests }}m
            memory: {{ .Values.memory_requests }}Mi
